
/:
  controller : "MainController" 
  action : "default"

/404:
  controller : "MainController" 
  action : "page404"

/login:
  controller : "SecurityController" 
  action : "login"

/logout:
  controller : "SecurityController" 
  action : "logout"

/register:
  controller : "SecurityController" 
  action : "register"

/notification:
  controller : "SettingsController"
  action : "notification"
